# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tophat}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Agalloco"]
  s.date = %q{2010-05-04}
  s.description = %q{simple view helpers for your layouts}
  s.email = %q{steve.agalloco@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "lib/tophat.rb",
     "lib/tophat/core_extensions.rb",
     "lib/tophat/meta.rb",
     "lib/tophat/stylesheet.rb",
     "lib/tophat/title.rb",
     "lib/tophat/version.rb",
     "rails/init.rb",
     "test/helper.rb",
     "test/test_tophat.rb",
     "test/test_tophat_meta.rb",
     "test/test_tophat_stylesheets.rb",
     "test/test_tophat_title.rb",
     "tophat.gemspec"
  ]
  s.homepage = %q{http://github.com/spagalloco/tophat}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{simple view helpers for your layouts}
  s.test_files = [
    "test/helper.rb",
     "test/test_tophat.rb",
     "test/test_tophat_meta.rb",
     "test/test_tophat_stylesheets.rb",
     "test/test_tophat_title.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.5"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<actionpack>, [">= 2.3.5"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 2.3.5"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

